# Generated by Django 5.0.2 on 2024-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.BigIntegerField(),
        ),
    ]
