# Generated by Django 5.0.2 on 2024-04-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_type',
            field=models.CharField(default='GA', max_length=100),
        ),
    ]
