# Generated by Django 5.0.2 on 2024-04-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ticket_type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
