# Generated by Django 4.2.10 on 2024-02-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_customuser_spotifyusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='spotifyUsername',
            field=models.CharField(blank=True, max_length=31, verbose_name='spotfify username'),
        ),
    ]
