# Generated by Django 5.0.2 on 2024-03-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_customuser_card_number_customuser_cardholder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cardholder_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='zip_code',
        ),
    ]
