# Generated by Django 5.0.2 on 2024-03-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='venueuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='venueuser',
            name='venue_image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
