# Generated by Django 5.0.2 on 2024-03-28 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue_auth', '0003_venueuser_venue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_time', models.PositiveIntegerField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_image_url', models.URLField(max_length=1024)),
                ('available_general_admission_tickets', models.PositiveIntegerField()),
                ('general_admission_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_vip_tickets', models.PositiveIntegerField()),
                ('vip_ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('venue_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='venue_auth.venueuser')),
            ],
        ),
    ]
