# Generated by Django 5.0.2 on 2024-04-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_alter_event_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue_user',
        ),
        migrations.AddField(
            model_name='event',
            name='venue_user_email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.CharField(max_length=255),
        ),
    ]
