# Generated by Django 5.0.2 on 2024-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_remove_event_venue_user_event_venue_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_user_email',
            field=models.CharField(max_length=100),
        ),
    ]
