# Generated by Django 5.0.2 on 2024-04-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
