name: Django CI/CD
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Build and push Docker Image
        run: |
          docker login --username bindudokala --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/bindudokala/p465-backend:latest --file ./RhythmReserve/Dockerfile .
          docker push ghcr.io/bindudokala/p465-backend:latest
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to Production
  #       run: |
  #         docker run -d -p 8000:8000 rhythmreserve